// Mock data layer — mirrors Convex schema for easy swap to live queries.

const now = Date.now();
const HOUR_MS = 3_600_000;
const DAY_MS = 86_400_000;

// ── Instances ────────────────────────────────────────────────────────────────

export const mockInstances = [
  {
    id: "instance_1",
    name: "Production Gateway",
    status: "online" as const,
    provider: "AWS",
    region: "us-east-1",
    agentCount: 3,
    version: "2.4.1",
    cpuUsage: 42,
    memoryUsage: 67,
    lastHeartbeat: now - 12_000,
    createdAt: now - 90 * DAY_MS,
  },
  {
    id: "instance_2",
    name: "Staging Server",
    status: "online" as const,
    provider: "GCP",
    region: "us-central1",
    agentCount: 2,
    version: "2.5.0-beta",
    cpuUsage: 18,
    memoryUsage: 34,
    lastHeartbeat: now - 8_000,
    createdAt: now - 45 * DAY_MS,
  },
  {
    id: "instance_3",
    name: "Dev Instance",
    status: "provisioning" as const,
    provider: "Azure",
    region: "westeurope",
    agentCount: 1,
    version: "2.5.0-rc1",
    cpuUsage: 5,
    memoryUsage: 12,
    lastHeartbeat: now - 120_000,
    createdAt: now - 3 * DAY_MS,
  },
];

// ── Agents ───────────────────────────────────────────────────────────────────

export const mockAgents = [
  {
    id: "agent_1",
    instanceId: "instance_1",
    name: "Support Agent",
    status: "active" as const,
    model: "gpt-4o",
    sessionCount: 142,
    totalTokens: 2_870_400,
    totalCost: 34.12,
    createdAt: now - 88 * DAY_MS,
  },
  {
    id: "agent_2",
    instanceId: "instance_1",
    name: "Research Agent",
    status: "active" as const,
    model: "claude-3.5-sonnet",
    sessionCount: 67,
    totalTokens: 5_420_000,
    totalCost: 81.30,
    createdAt: now - 60 * DAY_MS,
  },
  {
    id: "agent_3",
    instanceId: "instance_1",
    name: "Code Review Bot",
    status: "idle" as const,
    model: "gpt-4o",
    sessionCount: 213,
    totalTokens: 1_150_000,
    totalCost: 13.80,
    createdAt: now - 75 * DAY_MS,
  },
  {
    id: "agent_4",
    instanceId: "instance_2",
    name: "QA Tester",
    status: "active" as const,
    model: "gpt-4o-mini",
    sessionCount: 89,
    totalTokens: 940_000,
    totalCost: 4.70,
    createdAt: now - 30 * DAY_MS,
  },
  {
    id: "agent_5",
    instanceId: "instance_2",
    name: "Docs Writer",
    status: "paused" as const,
    model: "claude-3.5-sonnet",
    sessionCount: 34,
    totalTokens: 1_680_000,
    totalCost: 25.20,
    createdAt: now - 20 * DAY_MS,
  },
  {
    id: "agent_6",
    instanceId: "instance_3",
    name: "Dev Sandbox",
    status: "idle" as const,
    model: "gpt-4o",
    sessionCount: 5,
    totalTokens: 48_000,
    totalCost: 0.58,
    createdAt: now - 2 * DAY_MS,
  },
];

// ── Tasks ────────────────────────────────────────────────────────────────────

export const mockTasks = [
  {
    id: "task_1",
    userId: "user_demo",
    agentId: "agent_1",
    title: "Respond to Zendesk ticket #4812",
    description: "Customer reports intermittent 502 errors on /api/v2/widgets endpoint",
    status: "running" as const,
    priority: "high" as const,
    deadline: now + 2 * HOUR_MS,
    createdAt: now - 35 * 60_000,
  },
  {
    id: "task_2",
    userId: "user_demo",
    agentId: "agent_2",
    title: "Research competitor pricing changes",
    description: "Compile a summary of Q3 pricing updates from top 5 competitors",
    status: "done" as const,
    priority: "medium" as const,
    deadline: now - 1 * DAY_MS,
    createdAt: now - 3 * DAY_MS,
  },
  {
    id: "task_3",
    userId: "user_demo",
    agentId: "agent_3",
    title: "Review PR #287 — auth refactor",
    description: "Automated code review for the authentication module refactor",
    status: "needs_review" as const,
    priority: "high" as const,
    deadline: now + 4 * HOUR_MS,
    createdAt: now - 2 * HOUR_MS,
  },
  {
    id: "task_4",
    userId: "user_demo",
    agentId: "agent_4",
    title: "Run regression suite on staging",
    description: "Execute full E2E test suite against staging environment",
    status: "running" as const,
    priority: "high" as const,
    deadline: now + 1 * HOUR_MS,
    createdAt: now - 45 * 60_000,
  },
  {
    id: "task_5",
    userId: "user_demo",
    agentId: "agent_5",
    title: "Generate API changelog for v2.5",
    description: "Create human-readable changelog from commit history",
    status: "queued" as const,
    priority: "low" as const,
    deadline: now + 3 * DAY_MS,
    createdAt: now - 10 * 60_000,
  },
  {
    id: "task_6",
    userId: "user_demo",
    agentId: "agent_1",
    title: "Summarize weekly support metrics",
    description: "Aggregate ticket volume, resolution time, and CSAT scores",
    status: "done" as const,
    priority: "medium" as const,
    deadline: now - 2 * DAY_MS,
    createdAt: now - 5 * DAY_MS,
  },
  {
    id: "task_7",
    userId: "user_demo",
    agentId: "agent_2",
    title: "Draft blog post on AI safety",
    description: "Write a 1,500-word blog post covering recent AI safety research",
    status: "failed" as const,
    priority: "low" as const,
    deadline: now - 1 * DAY_MS,
    createdAt: now - 4 * DAY_MS,
  },
  {
    id: "task_8",
    userId: "user_demo",
    agentId: "agent_6",
    title: "Scaffold new microservice template",
    description: "Set up boilerplate for the notifications microservice",
    status: "queued" as const,
    priority: "medium" as const,
    deadline: now + 2 * DAY_MS,
    createdAt: now - 5 * 60_000,
  },
  {
    id: "task_9",
    userId: "user_demo",
    agentId: "agent_3",
    title: "Audit npm dependencies for CVEs",
    description: "Scan all production dependencies and flag critical vulnerabilities",
    status: "needs_review" as const,
    priority: "high" as const,
    deadline: now + 6 * HOUR_MS,
    createdAt: now - 3 * HOUR_MS,
  },
];

// ── Canvases ─────────────────────────────────────────────────────────────────

export const mockCanvases = [
  {
    id: "canvas_1",
    userId: "user_demo",
    agentId: "agent_1",
    title: "Support Dashboard",
    type: "dashboard" as const,
    content: JSON.stringify({
      widgets: [
        { type: "metric", label: "Open Tickets", value: 23 },
        { type: "metric", label: "Avg Resolution", value: "2.4h" },
        { type: "chart", label: "Tickets / Day", data: [18, 24, 15, 31, 22, 19, 23] },
      ],
    }),
    thumbnail: "/thumbnails/support-dashboard.png",
    createdAt: now - 14 * DAY_MS,
    updatedAt: now - 1 * HOUR_MS,
  },
  {
    id: "canvas_2",
    userId: "user_demo",
    agentId: "agent_2",
    title: "Competitor Analysis Board",
    type: "board" as const,
    content: JSON.stringify({
      columns: ["Backlog", "In Progress", "Done"],
      cards: [
        { title: "Acme Corp pricing", column: "Done" },
        { title: "Beta Inc features", column: "In Progress" },
        { title: "Gamma Ltd market share", column: "Backlog" },
      ],
    }),
    thumbnail: "/thumbnails/competitor-board.png",
    createdAt: now - 7 * DAY_MS,
    updatedAt: now - 3 * HOUR_MS,
  },
  {
    id: "canvas_3",
    userId: "user_demo",
    agentId: "agent_3",
    title: "PR Review Checklist",
    type: "form" as const,
    content: JSON.stringify({
      fields: [
        { label: "Security review", type: "checkbox", checked: true },
        { label: "Performance impact", type: "checkbox", checked: false },
        { label: "Test coverage", type: "checkbox", checked: true },
      ],
    }),
    thumbnail: "/thumbnails/pr-checklist.png",
    createdAt: now - 2 * DAY_MS,
    updatedAt: now - 30 * 60_000,
  },
  {
    id: "canvas_4",
    userId: "user_demo",
    agentId: "agent_4",
    title: "Test Coverage Report",
    type: "chart" as const,
    content: JSON.stringify({
      chartType: "bar",
      labels: ["Unit", "Integration", "E2E", "Smoke"],
      values: [92, 78, 64, 100],
    }),
    thumbnail: "/thumbnails/test-coverage.png",
    createdAt: now - 5 * DAY_MS,
    updatedAt: now - 12 * HOUR_MS,
  },
  {
    id: "canvas_5",
    userId: "user_demo",
    agentId: "agent_6",
    title: "Service Architecture Preview",
    type: "code_preview" as const,
    content: JSON.stringify({
      language: "yaml",
      code: "services:\n  api:\n    port: 3000\n  worker:\n    port: 3001\n  scheduler:\n    port: 3002",
    }),
    thumbnail: "/thumbnails/architecture.png",
    createdAt: now - 1 * DAY_MS,
    updatedAt: now - 6 * HOUR_MS,
  },
];

// ── Cron Jobs ────────────────────────────────────────────────────────────────

export const mockCronJobs = [
  {
    id: "cron_1",
    userId: "user_demo",
    agentId: "agent_1",
    name: "Daily Support Digest",
    schedule: "0 9 * * *",
    instruction: "Summarize open tickets and send digest to #support-team Slack channel",
    enabled: true,
    lastRunAt: now - 3 * HOUR_MS,
    lastRunStatus: "success" as const,
    nextRunAt: now + 21 * HOUR_MS,
    createdAt: now - 60 * DAY_MS,
  },
  {
    id: "cron_2",
    userId: "user_demo",
    agentId: "agent_2",
    name: "Weekly Market Scan",
    schedule: "0 8 * * 1",
    instruction: "Search for competitor product launches and pricing changes published in the last 7 days",
    enabled: true,
    lastRunAt: now - 2 * DAY_MS,
    lastRunStatus: "success" as const,
    nextRunAt: now + 5 * DAY_MS,
    createdAt: now - 40 * DAY_MS,
  },
  {
    id: "cron_3",
    userId: "user_demo",
    agentId: "agent_3",
    name: "Nightly Dependency Audit",
    schedule: "0 2 * * *",
    instruction: "Run npm audit on all repositories and report critical vulnerabilities",
    enabled: true,
    lastRunAt: now - 8 * HOUR_MS,
    lastRunStatus: "success" as const,
    nextRunAt: now + 16 * HOUR_MS,
    createdAt: now - 50 * DAY_MS,
  },
  {
    id: "cron_4",
    userId: "user_demo",
    agentId: "agent_4",
    name: "Staging Smoke Tests",
    schedule: "*/30 * * * *",
    instruction: "Run critical-path smoke tests against staging and alert on failure",
    enabled: true,
    lastRunAt: now - 18 * 60_000,
    lastRunStatus: "success" as const,
    nextRunAt: now + 12 * 60_000,
    createdAt: now - 25 * DAY_MS,
  },
  {
    id: "cron_5",
    userId: "user_demo",
    agentId: "agent_5",
    name: "Docs Freshness Check",
    schedule: "0 6 * * 3",
    instruction: "Identify documentation pages not updated in the last 30 days",
    enabled: false,
    lastRunAt: now - 10 * DAY_MS,
    lastRunStatus: "failed" as const,
    nextRunAt: undefined,
    createdAt: now - 15 * DAY_MS,
  },
  {
    id: "cron_6",
    userId: "user_demo",
    agentId: "agent_1",
    name: "Monthly Usage Report",
    schedule: "0 0 1 * *",
    instruction: "Generate usage and cost report for all agents and email to admin@example.com",
    enabled: true,
    lastRunAt: now - 18 * DAY_MS,
    lastRunStatus: "success" as const,
    nextRunAt: now + 12 * DAY_MS,
    createdAt: now - 80 * DAY_MS,
  },
];

// ── Approvals ────────────────────────────────────────────────────────────────

export const mockApprovals = [
  {
    id: "approval_1",
    userId: "user_demo",
    agentId: "agent_1",
    description: "Send refund of $249.99 to customer acme-corp",
    actionDetail: "Stripe refund via API: charge ch_3Nk…xYz, amount $249.99",
    riskLevel: "high" as const,
    status: "pending" as const,
    decidedBy: undefined,
    decidedAt: undefined,
    createdAt: now - 15 * 60_000,
  },
  {
    id: "approval_2",
    userId: "user_demo",
    agentId: "agent_2",
    description: "Publish competitive analysis report to public wiki",
    actionDetail: "Confluence API: create page in space 'RESEARCH', title 'Q3 Competitor Landscape'",
    riskLevel: "medium" as const,
    status: "pending" as const,
    decidedBy: undefined,
    decidedAt: undefined,
    createdAt: now - 45 * 60_000,
  },
  {
    id: "approval_3",
    userId: "user_demo",
    agentId: "agent_3",
    description: "Merge PR #287 into main branch",
    actionDetail: "GitHub API: merge pull/287, strategy 'squash'",
    riskLevel: "high" as const,
    status: "pending" as const,
    decidedBy: undefined,
    decidedAt: undefined,
    createdAt: now - 1 * HOUR_MS,
  },
  {
    id: "approval_4",
    userId: "user_demo",
    agentId: "agent_4",
    description: "Deploy staging build v2.5.0-beta.3 to production",
    actionDetail: "CI/CD pipeline: promote staging image sha-a1b2c3d to production cluster",
    riskLevel: "high" as const,
    status: "pending" as const,
    decidedBy: undefined,
    decidedAt: undefined,
    createdAt: now - 2 * HOUR_MS,
  },
  {
    id: "approval_5",
    userId: "user_demo",
    agentId: "agent_1",
    description: "Send bulk email campaign to 12,400 subscribers",
    actionDetail: "SendGrid API: send template tpl_welcome_back to segment seg_inactive_90d",
    riskLevel: "medium" as const,
    status: "pending" as const,
    decidedBy: undefined,
    decidedAt: undefined,
    createdAt: now - 3 * HOUR_MS,
  },
  {
    id: "approval_6",
    userId: "user_demo",
    agentId: "agent_2",
    description: "Access Google Analytics API for traffic report",
    actionDetail: "OAuth scope: analytics.readonly, property UA-123456-1",
    riskLevel: "low" as const,
    status: "approved" as const,
    decidedBy: "user_demo",
    decidedAt: now - 1 * DAY_MS,
    createdAt: now - 1 * DAY_MS - 30 * 60_000,
  },
  {
    id: "approval_7",
    userId: "user_demo",
    agentId: "agent_6",
    description: "Delete unused S3 bucket dev-temp-uploads",
    actionDetail: "AWS S3 API: delete bucket dev-temp-uploads (14 objects, 2.3 GB)",
    riskLevel: "high" as const,
    status: "rejected" as const,
    decidedBy: "user_demo",
    decidedAt: now - 2 * DAY_MS,
    createdAt: now - 2 * DAY_MS - 1 * HOUR_MS,
  },
];

// ── Usage Records ────────────────────────────────────────────────────────────

export const mockUsageRecords = [
  {
    id: "usage_1",
    userId: "user_demo",
    agentId: "agent_1",
    model: "gpt-4o",
    tokensUsed: 48_200,
    cost: 0.58,
    taskType: "support",
    date: new Date(now - 0 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 0 * DAY_MS,
  },
  {
    id: "usage_2",
    userId: "user_demo",
    agentId: "agent_2",
    model: "claude-3.5-sonnet",
    tokensUsed: 124_000,
    cost: 1.86,
    taskType: "research",
    date: new Date(now - 0 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 0 * DAY_MS,
  },
  {
    id: "usage_3",
    userId: "user_demo",
    agentId: "agent_3",
    model: "gpt-4o",
    tokensUsed: 31_400,
    cost: 0.38,
    taskType: "code_review",
    date: new Date(now - 1 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 1 * DAY_MS,
  },
  {
    id: "usage_4",
    userId: "user_demo",
    agentId: "agent_4",
    model: "gpt-4o-mini",
    tokensUsed: 67_800,
    cost: 0.34,
    taskType: "testing",
    date: new Date(now - 1 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 1 * DAY_MS,
  },
  {
    id: "usage_5",
    userId: "user_demo",
    agentId: "agent_1",
    model: "gpt-4o",
    tokensUsed: 52_100,
    cost: 0.63,
    taskType: "support",
    date: new Date(now - 2 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 2 * DAY_MS,
  },
  {
    id: "usage_6",
    userId: "user_demo",
    agentId: "agent_5",
    model: "claude-3.5-sonnet",
    tokensUsed: 89_300,
    cost: 1.34,
    taskType: "documentation",
    date: new Date(now - 2 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 2 * DAY_MS,
  },
  {
    id: "usage_7",
    userId: "user_demo",
    agentId: "agent_2",
    model: "claude-3.5-sonnet",
    tokensUsed: 142_000,
    cost: 2.13,
    taskType: "research",
    date: new Date(now - 3 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 3 * DAY_MS,
  },
  {
    id: "usage_8",
    userId: "user_demo",
    agentId: "agent_3",
    model: "gpt-4o",
    tokensUsed: 27_600,
    cost: 0.33,
    taskType: "code_review",
    date: new Date(now - 4 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 4 * DAY_MS,
  },
  {
    id: "usage_9",
    userId: "user_demo",
    agentId: "agent_6",
    model: "gpt-4o",
    tokensUsed: 8_400,
    cost: 0.10,
    taskType: "development",
    date: new Date(now - 5 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 5 * DAY_MS,
  },
  {
    id: "usage_10",
    userId: "user_demo",
    agentId: "agent_4",
    model: "gpt-4o-mini",
    tokensUsed: 54_200,
    cost: 0.27,
    taskType: "testing",
    date: new Date(now - 6 * DAY_MS).toISOString().slice(0, 10),
    createdAt: now - 6 * DAY_MS,
  },
];

// ── Discover Items ───────────────────────────────────────────────────────────

export const mockDiscoverItems = [
  // Skills
  {
    id: "discover_1",
    type: "skill" as const,
    title: "Web Scraper Pro",
    description: "Extract structured data from any website with anti-bot bypass and rate limiting",
    author: "claw-labs",
    category: "Data Collection",
    tags: ["scraping", "data", "web"],
    installCount: 3_420,
    rating: 4.7,
    createdAt: now - 120 * DAY_MS,
  },
  {
    id: "discover_2",
    type: "skill" as const,
    title: "SQL Query Builder",
    description: "Generate and execute safe SQL queries from natural language descriptions",
    author: "datacraft",
    category: "Database",
    tags: ["sql", "database", "query"],
    installCount: 8_150,
    rating: 4.9,
    createdAt: now - 200 * DAY_MS,
  },
  {
    id: "discover_3",
    type: "skill" as const,
    title: "Image Analyzer",
    description: "Describe, classify, and extract text from images using vision models",
    author: "visionworks",
    category: "Media",
    tags: ["vision", "ocr", "image"],
    installCount: 5_670,
    rating: 4.5,
    createdAt: now - 90 * DAY_MS,
  },
  // Automations
  {
    id: "discover_4",
    type: "automation" as const,
    title: "PR Review Pipeline",
    description: "Automatically review pull requests for style, security, and test coverage",
    author: "devops-guild",
    category: "CI/CD",
    tags: ["github", "code-review", "automation"],
    installCount: 12_300,
    rating: 4.8,
    createdAt: now - 180 * DAY_MS,
  },
  {
    id: "discover_5",
    type: "automation" as const,
    title: "Customer Onboarding Flow",
    description: "End-to-end automated onboarding: welcome email, CRM entry, Slack invite, and docs access",
    author: "growthops",
    category: "Sales",
    tags: ["onboarding", "crm", "email"],
    installCount: 2_890,
    rating: 4.4,
    createdAt: now - 60 * DAY_MS,
  },
  {
    id: "discover_6",
    type: "automation" as const,
    title: "Incident Response Playbook",
    description: "Detect anomalies, page on-call, open incident channel, and compile postmortem",
    author: "sre-collective",
    category: "Operations",
    tags: ["incident", "monitoring", "sre"],
    installCount: 6_710,
    rating: 4.6,
    createdAt: now - 150 * DAY_MS,
  },
  // Showcases
  {
    id: "discover_7",
    type: "showcase" as const,
    title: "AI-Powered Helpdesk",
    description: "Full-stack support desk with AI triage, auto-responses, and escalation workflows",
    author: "supportify",
    category: "Customer Support",
    tags: ["helpdesk", "support", "ai"],
    installCount: 1_540,
    rating: 4.3,
    createdAt: now - 30 * DAY_MS,
  },
  {
    id: "discover_8",
    type: "showcase" as const,
    title: "Research Assistant Suite",
    description: "Multi-agent research pipeline with source verification and citation management",
    author: "academi-ai",
    category: "Research",
    tags: ["research", "citations", "academic"],
    installCount: 980,
    rating: 4.6,
    createdAt: now - 45 * DAY_MS,
  },
  {
    id: "discover_9",
    type: "showcase" as const,
    title: "DevOps Command Center",
    description: "Unified dashboard for deployments, monitoring, and infrastructure management",
    author: "infra-ai",
    category: "DevOps",
    tags: ["devops", "infrastructure", "monitoring"],
    installCount: 2_210,
    rating: 4.8,
    createdAt: now - 75 * DAY_MS,
  },
];

// ── Browser Sessions ─────────────────────────────────────────────────────────

export const mockBrowserSessions = [
  {
    id: "browser_1",
    userId: "user_demo",
    agentId: "agent_2",
    url: "https://news.ycombinator.com",
    taskDescription: "Scan front page for AI-related articles and summarize top 5",
    status: "completed" as const,
    pagesVisited: [
      "https://news.ycombinator.com",
      "https://news.ycombinator.com/item?id=39812345",
      "https://news.ycombinator.com/item?id=39814567",
    ],
    outcome: "Found 5 AI-related articles; summary saved to memory file research/hn-digest.md",
    createdAt: now - 4 * HOUR_MS,
  },
  {
    id: "browser_2",
    userId: "user_demo",
    agentId: "agent_1",
    url: "https://status.stripe.com",
    taskDescription: "Check Stripe API status for any ongoing incidents",
    status: "completed" as const,
    pagesVisited: [
      "https://status.stripe.com",
      "https://status.stripe.com/incidents/rk4m8y6nj92q",
    ],
    outcome: "All systems operational; one resolved incident from 6 hours ago (payments latency)",
    createdAt: now - 6 * HOUR_MS,
  },
  {
    id: "browser_3",
    userId: "user_demo",
    agentId: "agent_4",
    url: "https://staging.example.com/login",
    taskDescription: "Run visual regression test on login page after CSS update",
    status: "active" as const,
    pagesVisited: [
      "https://staging.example.com/login",
      "https://staging.example.com/dashboard",
    ],
    outcome: undefined,
    createdAt: now - 10 * 60_000,
  },
  {
    id: "browser_4",
    userId: "user_demo",
    agentId: "agent_2",
    url: "https://arxiv.org/list/cs.AI/recent",
    taskDescription: "Find papers on multi-agent coordination published in the last 7 days",
    status: "failed" as const,
    pagesVisited: [
      "https://arxiv.org/list/cs.AI/recent",
    ],
    outcome: "Failed: rate-limited by arxiv.org after 3 requests; retrying in 60 minutes",
    createdAt: now - 1 * HOUR_MS,
  },
];

// ── Nodes ────────────────────────────────────────────────────────────────────

export const mockNodes = [
  {
    id: "node_1",
    userId: "user_demo",
    name: "MacBook Pro — Work",
    deviceType: "macos" as const,
    status: "online" as const,
    osVersion: "macOS 15.1 Sequoia",
    capabilities: {
      camera: true,
      screenRecord: true,
      location: true,
      notifications: true,
      voiceWake: true,
    },
    lastSeen: now - 30_000,
    createdAt: now - 180 * DAY_MS,
  },
  {
    id: "node_2",
    userId: "user_demo",
    name: "iPhone 16 Pro",
    deviceType: "iphone" as const,
    status: "online" as const,
    osVersion: "iOS 18.2",
    capabilities: {
      camera: true,
      screenRecord: false,
      location: true,
      notifications: true,
      voiceWake: true,
    },
    lastSeen: now - 120_000,
    createdAt: now - 90 * DAY_MS,
  },
  {
    id: "node_3",
    userId: "user_demo",
    name: "Ubuntu Build Server",
    deviceType: "linux" as const,
    status: "sleeping" as const,
    osVersion: "Ubuntu 24.04 LTS",
    capabilities: {
      camera: false,
      screenRecord: false,
      location: false,
      notifications: true,
      voiceWake: false,
    },
    lastSeen: now - 8 * HOUR_MS,
    createdAt: now - 365 * DAY_MS,
  },
  {
    id: "node_4",
    userId: "user_demo",
    name: "Pixel 9",
    deviceType: "android" as const,
    status: "offline" as const,
    osVersion: "Android 15",
    capabilities: {
      camera: true,
      screenRecord: true,
      location: true,
      notifications: true,
      voiceWake: false,
    },
    lastSeen: now - 3 * DAY_MS,
    createdAt: now - 60 * DAY_MS,
  },
];

// ── Memory Files ─────────────────────────────────────────────────────────────

export const mockMemoryFiles = [
  {
    id: "mem_1",
    userId: "user_demo",
    agentId: "agent_1",
    path: "support/escalation-rules.md",
    content: "# Escalation Rules\n\n1. VIP customers → immediate human handoff\n2. Billing disputes > $500 → manager approval\n3. Security incidents → page on-call SRE",
    fileType: "markdown",
    tags: ["support", "rules", "escalation"],
    createdAt: now - 60 * DAY_MS,
  },
  {
    id: "mem_2",
    userId: "user_demo",
    agentId: "agent_2",
    path: "research/competitor-profiles.json",
    content: JSON.stringify({ competitors: ["AcmeCorp", "BetaInc", "GammaLtd"], lastUpdated: new Date(now - 2 * DAY_MS).toISOString() }),
    fileType: "json",
    tags: ["research", "competitors"],
    createdAt: now - 30 * DAY_MS,
  },
  {
    id: "mem_3",
    userId: "user_demo",
    agentId: "agent_3",
    path: "code-review/style-guide.md",
    content: "# Code Review Style Guide\n\n- Prefer `const` over `let`\n- Max function length: 40 lines\n- Always handle error cases\n- Use descriptive variable names",
    fileType: "markdown",
    tags: ["code-review", "style", "guidelines"],
    createdAt: now - 45 * DAY_MS,
  },
  {
    id: "mem_4",
    userId: "user_demo",
    agentId: "agent_1",
    path: "support/canned-responses.md",
    content: "# Canned Responses\n\n## Billing\n- Refund processed: 'Your refund of {amount} has been initiated…'\n- Payment failed: 'We noticed your payment method…'",
    fileType: "markdown",
    tags: ["support", "templates", "billing"],
    createdAt: now - 50 * DAY_MS,
  },
  {
    id: "mem_5",
    userId: "user_demo",
    agentId: "agent_4",
    path: "qa/test-matrix.csv",
    content: "browser,os,status\nChrome 120,macOS,pass\nFirefox 121,Ubuntu,pass\nSafari 17,macOS,fail\nEdge 120,Windows,pass",
    fileType: "csv",
    tags: ["qa", "testing", "matrix"],
    createdAt: now - 10 * DAY_MS,
  },
  {
    id: "mem_6",
    userId: "user_demo",
    agentId: "agent_2",
    path: "research/hn-digest.md",
    content: "# HN Digest — Today\n\n1. **Multi-agent LLM orchestration** (342 points)\n2. **New GPT-4o benchmarks** (289 points)\n3. **Open-source voice assistant** (267 points)",
    fileType: "markdown",
    tags: ["research", "digest", "hackernews"],
    createdAt: now - 4 * HOUR_MS,
  },
];

// ── Audit Logs ───────────────────────────────────────────────────────────────

export const mockAuditLogs = [
  {
    id: "audit_1",
    orgId: "org_demo",
    userId: "user_demo",
    action: "bash",
    resourceType: "tool_call",
    resourceId: "agent_1",
    details: "Executed: ls -la /workspace/src",
    createdAt: now - 2 * HOUR_MS,
  },
  {
    id: "audit_2",
    orgId: "org_demo",
    userId: "user_demo",
    action: "update_model",
    resourceType: "config_change",
    resourceId: "agent_2",
    details: "Changed model from claude-3.5-haiku to claude-3.5-sonnet",
    createdAt: now - 5 * HOUR_MS,
  },
  {
    id: "audit_3",
    orgId: "org_demo",
    userId: "user_demo",
    action: "login",
    resourceType: "auth",
    resourceId: "user_demo",
    details: "Login from 192.168.1.10",
    createdAt: now - 8 * HOUR_MS,
  },
  {
    id: "audit_4",
    orgId: "org_demo",
    userId: "user_demo",
    action: "quarantine",
    resourceType: "security",
    resourceId: "agent_5",
    details: "Agent quarantined: policy violation detected",
    createdAt: now - 1 * DAY_MS,
  },
];

// ── Blueprints ────────────────────────────────────────────────────────────────

export const mockBlueprints = [
  {
    id: "bp_1",
    name: "Customer Support Agent",
    description: "GPT-4o powered support agent with triage, escalation, and canned-response skills. Connects to your ticketing system and Slack.",
    version: "2.1.0",
    status: "published" as const,
    deployCount: 14,
    createdAt: now - 60 * DAY_MS,
  },
  {
    id: "bp_2",
    name: "Research Assistant",
    description: "Multi-step research pipeline. Searches the web, reads papers, synthesizes findings into structured summaries.",
    version: "1.4.3",
    status: "published" as const,
    deployCount: 8,
    createdAt: now - 40 * DAY_MS,
  },
  {
    id: "bp_3",
    name: "Code Review Bot",
    description: "Runs on PR webhooks. Performs AST analysis, security scanning, test coverage checks, and posts structured review comments.",
    version: "3.0.0-beta",
    status: "draft" as const,
    deployCount: 2,
    createdAt: now - 7 * DAY_MS,
  },
];

// ── Voice Settings ───────────────────────────────────────────────────────────

export const mockVoiceSettings = {
  id: "voice_1",
  userId: "user_demo",
  wakeWord: "Hey Claw",
  ttsVoice: "alloy",
  speakingRate: 1.1,
  sttEngine: "whisper-v3",
  language: "en-US",
  enabled: true,
  createdAt: now - 30 * DAY_MS,
};
