/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardFleetIndexRouteImport } from './routes/_dashboard/fleet/index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/_dashboard/agents/index'
import { Route as DashboardAgentsNewRouteImport } from './routes/_dashboard/agents/new'
import { Route as DashboardFleetInstancesIndexRouteImport } from './routes/_dashboard/fleet/instances/index'
import { Route as DashboardAgentsAgentIdIndexRouteImport } from './routes/_dashboard/agents/$agentId/index'
import { Route as DashboardFleetInstancesNewRouteImport } from './routes/_dashboard/fleet/instances/new'
import { Route as DashboardFleetInstancesInstanceIdIndexRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFleetIndexRoute = DashboardFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsNewRoute = DashboardAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFleetInstancesIndexRoute =
  DashboardFleetInstancesIndexRouteImport.update({
    id: '/fleet/instances/',
    path: '/fleet/instances/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdIndexRoute =
  DashboardAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesNewRoute =
  DashboardFleetInstancesNewRouteImport.update({
    id: '/fleet/instances/new',
    path: '/fleet/instances/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdIndexRoute =
  DashboardFleetInstancesInstanceIdIndexRouteImport.update({
    id: '/fleet/instances/$instanceId/',
    path: '/fleet/instances/$instanceId/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/new': typeof DashboardAgentsNewRoute
  '/agents/': typeof DashboardAgentsIndexRoute
  '/fleet/': typeof DashboardFleetIndexRoute
  '/fleet/instances/new': typeof DashboardFleetInstancesNewRoute
  '/agents/$agentId/': typeof DashboardAgentsAgentIdIndexRoute
  '/fleet/instances/': typeof DashboardFleetInstancesIndexRoute
  '/fleet/instances/$instanceId/': typeof DashboardFleetInstancesInstanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/new': typeof DashboardAgentsNewRoute
  '/agents': typeof DashboardAgentsIndexRoute
  '/fleet': typeof DashboardFleetIndexRoute
  '/fleet/instances/new': typeof DashboardFleetInstancesNewRoute
  '/agents/$agentId': typeof DashboardAgentsAgentIdIndexRoute
  '/fleet/instances': typeof DashboardFleetInstancesIndexRoute
  '/fleet/instances/$instanceId': typeof DashboardFleetInstancesInstanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/agents/new': typeof DashboardAgentsNewRoute
  '/_dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/_dashboard/fleet/': typeof DashboardFleetIndexRoute
  '/_dashboard/fleet/instances/new': typeof DashboardFleetInstancesNewRoute
  '/_dashboard/agents/$agentId/': typeof DashboardAgentsAgentIdIndexRoute
  '/_dashboard/fleet/instances/': typeof DashboardFleetInstancesIndexRoute
  '/_dashboard/fleet/instances/$instanceId/': typeof DashboardFleetInstancesInstanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/new'
    | '/agents/'
    | '/fleet/'
    | '/fleet/instances/new'
    | '/agents/$agentId/'
    | '/fleet/instances/'
    | '/fleet/instances/$instanceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/new'
    | '/agents'
    | '/fleet'
    | '/fleet/instances/new'
    | '/agents/$agentId'
    | '/fleet/instances'
    | '/fleet/instances/$instanceId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/agents/new'
    | '/_dashboard/agents/'
    | '/_dashboard/fleet/'
    | '/_dashboard/fleet/instances/new'
    | '/_dashboard/agents/$agentId/'
    | '/_dashboard/fleet/instances/'
    | '/_dashboard/fleet/instances/$instanceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/fleet/': {
      id: '/_dashboard/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof DashboardFleetIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/': {
      id: '/_dashboard/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/new': {
      id: '/_dashboard/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof DashboardAgentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/': {
      id: '/_dashboard/fleet/instances/'
      path: '/fleet/instances'
      fullPath: '/fleet/instances/'
      preLoaderRoute: typeof DashboardFleetInstancesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/': {
      id: '/_dashboard/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof DashboardAgentsAgentIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/new': {
      id: '/_dashboard/fleet/instances/new'
      path: '/fleet/instances/new'
      fullPath: '/fleet/instances/new'
      preLoaderRoute: typeof DashboardFleetInstancesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/': {
      id: '/_dashboard/fleet/instances/$instanceId/'
      path: '/fleet/instances/$instanceId'
      fullPath: '/fleet/instances/$instanceId/'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgentsNewRoute: typeof DashboardAgentsNewRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
  DashboardFleetIndexRoute: typeof DashboardFleetIndexRoute
  DashboardFleetInstancesNewRoute: typeof DashboardFleetInstancesNewRoute
  DashboardAgentsAgentIdIndexRoute: typeof DashboardAgentsAgentIdIndexRoute
  DashboardFleetInstancesIndexRoute: typeof DashboardFleetInstancesIndexRoute
  DashboardFleetInstancesInstanceIdIndexRoute: typeof DashboardFleetInstancesInstanceIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsNewRoute: DashboardAgentsNewRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
  DashboardFleetIndexRoute: DashboardFleetIndexRoute,
  DashboardFleetInstancesNewRoute: DashboardFleetInstancesNewRoute,
  DashboardAgentsAgentIdIndexRoute: DashboardAgentsAgentIdIndexRoute,
  DashboardFleetInstancesIndexRoute: DashboardFleetInstancesIndexRoute,
  DashboardFleetInstancesInstanceIdIndexRoute:
    DashboardFleetInstancesInstanceIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
