/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as DashboardSwarmsIndexRouteImport } from './routes/_dashboard/swarms/index'
import { Route as DashboardSkillsIndexRouteImport } from './routes/_dashboard/skills/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardSessionsIndexRouteImport } from './routes/_dashboard/sessions/index'
import { Route as DashboardSecurityIndexRouteImport } from './routes/_dashboard/security/index'
import { Route as DashboardObserveIndexRouteImport } from './routes/_dashboard/observe/index'
import { Route as DashboardFleetIndexRouteImport } from './routes/_dashboard/fleet/index'
import { Route as DashboardConfigureIndexRouteImport } from './routes/_dashboard/configure/index'
import { Route as DashboardChannelsIndexRouteImport } from './routes/_dashboard/channels/index'
import { Route as DashboardBlueprintsIndexRouteImport } from './routes/_dashboard/blueprints/index'
import { Route as DashboardAuditIndexRouteImport } from './routes/_dashboard/audit/index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/_dashboard/agents/index'
import { Route as AppWorkIndexRouteImport } from './routes/_app/work/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppPersonalIndexRouteImport } from './routes/_app/personal/index'
import { Route as AppCronIndexRouteImport } from './routes/_app/cron/index'
import { Route as AppChatIndexRouteImport } from './routes/_app/chat/index'
import { Route as AppBriefingIndexRouteImport } from './routes/_app/briefing/index'
import { Route as AppAutomationsIndexRouteImport } from './routes/_app/automations/index'
import { Route as AppApprovalsIndexRouteImport } from './routes/_app/approvals/index'
import { Route as DashboardSecuritySecretsRouteImport } from './routes/_dashboard/security/secrets'
import { Route as DashboardSecurityQuarantineRouteImport } from './routes/_dashboard/security/quarantine'
import { Route as DashboardSecurityPostureRouteImport } from './routes/_dashboard/security/posture'
import { Route as DashboardSecurityIncidentsRouteImport } from './routes/_dashboard/security/incidents'
import { Route as DashboardObserveTracesRouteImport } from './routes/_dashboard/observe/traces'
import { Route as DashboardObserveLogsRouteImport } from './routes/_dashboard/observe/logs'
import { Route as DashboardObserveLiveRouteImport } from './routes/_dashboard/observe/live'
import { Route as DashboardObserveCostRouteImport } from './routes/_dashboard/observe/cost'
import { Route as DashboardAuditToolsRouteImport } from './routes/_dashboard/audit/tools'
import { Route as DashboardAuditConfigChangesRouteImport } from './routes/_dashboard/audit/config-changes'
import { Route as DashboardAgentsNewRouteImport } from './routes/_dashboard/agents/new'
import { Route as AppChatAgentIdRouteImport } from './routes/_app/chat/$agentId'
import { Route as DashboardSwarmsSwarmIdIndexRouteImport } from './routes/_dashboard/swarms/$swarmId/index'
import { Route as DashboardSessionsSessionIdIndexRouteImport } from './routes/_dashboard/sessions/$sessionId/index'
import { Route as DashboardFleetInstancesIndexRouteImport } from './routes/_dashboard/fleet/instances/index'
import { Route as DashboardBlueprintsBlueprintIdIndexRouteImport } from './routes/_dashboard/blueprints/$blueprintId/index'
import { Route as DashboardAgentsAgentIdIndexRouteImport } from './routes/_dashboard/agents/$agentId/index'
import { Route as DashboardFleetInstancesNewRouteImport } from './routes/_dashboard/fleet/instances/new'
import { Route as DashboardFleetInstancesInstanceIdIndexRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/index'
import { Route as DashboardAgentsAgentIdToolsIndexRouteImport } from './routes/_dashboard/agents/$agentId/tools/index'
import { Route as DashboardAgentsAgentIdPersonalityIndexRouteImport } from './routes/_dashboard/agents/$agentId/personality/index'
import { Route as DashboardAgentsAgentIdObserveIndexRouteImport } from './routes/_dashboard/agents/$agentId/observe/index'
import { Route as DashboardAgentsAgentIdModelIndexRouteImport } from './routes/_dashboard/agents/$agentId/model/index'
import { Route as DashboardAgentsAgentIdMemoryIndexRouteImport } from './routes/_dashboard/agents/$agentId/memory/index'
import { Route as DashboardAgentsAgentIdPersonalityUserMdRouteImport } from './routes/_dashboard/agents/$agentId/personality/user-md'
import { Route as DashboardAgentsAgentIdPersonalitySoulRouteImport } from './routes/_dashboard/agents/$agentId/personality/soul'
import { Route as DashboardAgentsAgentIdPersonalityAgentsMdRouteImport } from './routes/_dashboard/agents/$agentId/personality/agents-md'
import { Route as DashboardFleetInstancesInstanceIdPersonalitiesIndexRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/personalities/index'
import { Route as DashboardFleetInstancesInstanceIdConfigIndexRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/config/index'
import { Route as DashboardFleetInstancesInstanceIdPersonalitiesSoulRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/personalities/soul'
import { Route as DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/personalities/agents-md'
import { Route as DashboardFleetInstancesInstanceIdConfigToolsRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/config/tools'
import { Route as DashboardFleetInstancesInstanceIdConfigProvidersRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/config/providers'
import { Route as DashboardFleetInstancesInstanceIdConfigPoliciesRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/config/policies'
import { Route as DashboardFleetInstancesInstanceIdConfigGeneralRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/config/general'
import { Route as DashboardFleetInstancesInstanceIdConfigEnvironmentRouteImport } from './routes/_dashboard/fleet/instances/$instanceId/config/environment'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const DashboardSwarmsIndexRoute = DashboardSwarmsIndexRouteImport.update({
  id: '/swarms/',
  path: '/swarms/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkillsIndexRoute = DashboardSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsIndexRoute = DashboardSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityIndexRoute = DashboardSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObserveIndexRoute = DashboardObserveIndexRouteImport.update({
  id: '/observe/',
  path: '/observe/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFleetIndexRoute = DashboardFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigureIndexRoute = DashboardConfigureIndexRouteImport.update({
  id: '/configure/',
  path: '/configure/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsIndexRoute = DashboardChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlueprintsIndexRoute =
  DashboardBlueprintsIndexRouteImport.update({
    id: '/blueprints/',
    path: '/blueprints/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAuditIndexRoute = DashboardAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DashboardRoute,
} as any)
const AppWorkIndexRoute = AppWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalIndexRoute = AppPersonalIndexRouteImport.update({
  id: '/personal/',
  path: '/personal/',
  getParentRoute: () => AppRoute,
} as any)
const AppCronIndexRoute = AppCronIndexRouteImport.update({
  id: '/cron/',
  path: '/cron/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppBriefingIndexRoute = AppBriefingIndexRouteImport.update({
  id: '/briefing/',
  path: '/briefing/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsIndexRoute = AppAutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsIndexRoute = AppApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AppRoute,
} as any)
const DashboardSecuritySecretsRoute =
  DashboardSecuritySecretsRouteImport.update({
    id: '/security/secrets',
    path: '/security/secrets',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSecurityQuarantineRoute =
  DashboardSecurityQuarantineRouteImport.update({
    id: '/security/quarantine',
    path: '/security/quarantine',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSecurityPostureRoute =
  DashboardSecurityPostureRouteImport.update({
    id: '/security/posture',
    path: '/security/posture',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSecurityIncidentsRoute =
  DashboardSecurityIncidentsRouteImport.update({
    id: '/security/incidents',
    path: '/security/incidents',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardObserveTracesRoute = DashboardObserveTracesRouteImport.update({
  id: '/observe/traces',
  path: '/observe/traces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObserveLogsRoute = DashboardObserveLogsRouteImport.update({
  id: '/observe/logs',
  path: '/observe/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObserveLiveRoute = DashboardObserveLiveRouteImport.update({
  id: '/observe/live',
  path: '/observe/live',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObserveCostRoute = DashboardObserveCostRouteImport.update({
  id: '/observe/cost',
  path: '/observe/cost',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditToolsRoute = DashboardAuditToolsRouteImport.update({
  id: '/audit/tools',
  path: '/audit/tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditConfigChangesRoute =
  DashboardAuditConfigChangesRouteImport.update({
    id: '/audit/config-changes',
    path: '/audit/config-changes',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsNewRoute = DashboardAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => DashboardRoute,
} as any)
const AppChatAgentIdRoute = AppChatAgentIdRouteImport.update({
  id: '/chat/$agentId',
  path: '/chat/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const DashboardSwarmsSwarmIdIndexRoute =
  DashboardSwarmsSwarmIdIndexRouteImport.update({
    id: '/swarms/$swarmId/',
    path: '/swarms/$swarmId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSessionsSessionIdIndexRoute =
  DashboardSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesIndexRoute =
  DashboardFleetInstancesIndexRouteImport.update({
    id: '/fleet/instances/',
    path: '/fleet/instances/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBlueprintsBlueprintIdIndexRoute =
  DashboardBlueprintsBlueprintIdIndexRouteImport.update({
    id: '/blueprints/$blueprintId/',
    path: '/blueprints/$blueprintId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdIndexRoute =
  DashboardAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesNewRoute =
  DashboardFleetInstancesNewRouteImport.update({
    id: '/fleet/instances/new',
    path: '/fleet/instances/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdIndexRoute =
  DashboardFleetInstancesInstanceIdIndexRouteImport.update({
    id: '/fleet/instances/$instanceId/',
    path: '/fleet/instances/$instanceId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdToolsIndexRoute =
  DashboardAgentsAgentIdToolsIndexRouteImport.update({
    id: '/agents/$agentId/tools/',
    path: '/agents/$agentId/tools/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdPersonalityIndexRoute =
  DashboardAgentsAgentIdPersonalityIndexRouteImport.update({
    id: '/agents/$agentId/personality/',
    path: '/agents/$agentId/personality/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdObserveIndexRoute =
  DashboardAgentsAgentIdObserveIndexRouteImport.update({
    id: '/agents/$agentId/observe/',
    path: '/agents/$agentId/observe/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdModelIndexRoute =
  DashboardAgentsAgentIdModelIndexRouteImport.update({
    id: '/agents/$agentId/model/',
    path: '/agents/$agentId/model/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdMemoryIndexRoute =
  DashboardAgentsAgentIdMemoryIndexRouteImport.update({
    id: '/agents/$agentId/memory/',
    path: '/agents/$agentId/memory/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdPersonalityUserMdRoute =
  DashboardAgentsAgentIdPersonalityUserMdRouteImport.update({
    id: '/agents/$agentId/personality/user-md',
    path: '/agents/$agentId/personality/user-md',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdPersonalitySoulRoute =
  DashboardAgentsAgentIdPersonalitySoulRouteImport.update({
    id: '/agents/$agentId/personality/soul',
    path: '/agents/$agentId/personality/soul',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdPersonalityAgentsMdRoute =
  DashboardAgentsAgentIdPersonalityAgentsMdRouteImport.update({
    id: '/agents/$agentId/personality/agents-md',
    path: '/agents/$agentId/personality/agents-md',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdPersonalitiesIndexRoute =
  DashboardFleetInstancesInstanceIdPersonalitiesIndexRouteImport.update({
    id: '/fleet/instances/$instanceId/personalities/',
    path: '/fleet/instances/$instanceId/personalities/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdConfigIndexRoute =
  DashboardFleetInstancesInstanceIdConfigIndexRouteImport.update({
    id: '/fleet/instances/$instanceId/config/',
    path: '/fleet/instances/$instanceId/config/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdPersonalitiesSoulRoute =
  DashboardFleetInstancesInstanceIdPersonalitiesSoulRouteImport.update({
    id: '/fleet/instances/$instanceId/personalities/soul',
    path: '/fleet/instances/$instanceId/personalities/soul',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRoute =
  DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRouteImport.update({
    id: '/fleet/instances/$instanceId/personalities/agents-md',
    path: '/fleet/instances/$instanceId/personalities/agents-md',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdConfigToolsRoute =
  DashboardFleetInstancesInstanceIdConfigToolsRouteImport.update({
    id: '/fleet/instances/$instanceId/config/tools',
    path: '/fleet/instances/$instanceId/config/tools',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdConfigProvidersRoute =
  DashboardFleetInstancesInstanceIdConfigProvidersRouteImport.update({
    id: '/fleet/instances/$instanceId/config/providers',
    path: '/fleet/instances/$instanceId/config/providers',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdConfigPoliciesRoute =
  DashboardFleetInstancesInstanceIdConfigPoliciesRouteImport.update({
    id: '/fleet/instances/$instanceId/config/policies',
    path: '/fleet/instances/$instanceId/config/policies',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdConfigGeneralRoute =
  DashboardFleetInstancesInstanceIdConfigGeneralRouteImport.update({
    id: '/fleet/instances/$instanceId/config/general',
    path: '/fleet/instances/$instanceId/config/general',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFleetInstancesInstanceIdConfigEnvironmentRoute =
  DashboardFleetInstancesInstanceIdConfigEnvironmentRouteImport.update({
    id: '/fleet/instances/$instanceId/config/environment',
    path: '/fleet/instances/$instanceId/config/environment',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AppHomeRoute
  '/chat/$agentId': typeof AppChatAgentIdRoute
  '/agents/new': typeof DashboardAgentsNewRoute
  '/audit/config-changes': typeof DashboardAuditConfigChangesRoute
  '/audit/tools': typeof DashboardAuditToolsRoute
  '/observe/cost': typeof DashboardObserveCostRoute
  '/observe/live': typeof DashboardObserveLiveRoute
  '/observe/logs': typeof DashboardObserveLogsRoute
  '/observe/traces': typeof DashboardObserveTracesRoute
  '/security/incidents': typeof DashboardSecurityIncidentsRoute
  '/security/posture': typeof DashboardSecurityPostureRoute
  '/security/quarantine': typeof DashboardSecurityQuarantineRoute
  '/security/secrets': typeof DashboardSecuritySecretsRoute
  '/approvals/': typeof AppApprovalsIndexRoute
  '/automations/': typeof AppAutomationsIndexRoute
  '/briefing/': typeof AppBriefingIndexRoute
  '/chat/': typeof AppChatIndexRoute
  '/cron/': typeof AppCronIndexRoute
  '/personal/': typeof AppPersonalIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/work/': typeof AppWorkIndexRoute
  '/agents/': typeof DashboardAgentsIndexRoute
  '/audit/': typeof DashboardAuditIndexRoute
  '/blueprints/': typeof DashboardBlueprintsIndexRoute
  '/channels/': typeof DashboardChannelsIndexRoute
  '/configure/': typeof DashboardConfigureIndexRoute
  '/fleet/': typeof DashboardFleetIndexRoute
  '/observe/': typeof DashboardObserveIndexRoute
  '/security/': typeof DashboardSecurityIndexRoute
  '/sessions/': typeof DashboardSessionsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/skills/': typeof DashboardSkillsIndexRoute
  '/swarms/': typeof DashboardSwarmsIndexRoute
  '/fleet/instances/new': typeof DashboardFleetInstancesNewRoute
  '/agents/$agentId/': typeof DashboardAgentsAgentIdIndexRoute
  '/blueprints/$blueprintId/': typeof DashboardBlueprintsBlueprintIdIndexRoute
  '/fleet/instances/': typeof DashboardFleetInstancesIndexRoute
  '/sessions/$sessionId/': typeof DashboardSessionsSessionIdIndexRoute
  '/swarms/$swarmId/': typeof DashboardSwarmsSwarmIdIndexRoute
  '/agents/$agentId/personality/agents-md': typeof DashboardAgentsAgentIdPersonalityAgentsMdRoute
  '/agents/$agentId/personality/soul': typeof DashboardAgentsAgentIdPersonalitySoulRoute
  '/agents/$agentId/personality/user-md': typeof DashboardAgentsAgentIdPersonalityUserMdRoute
  '/agents/$agentId/memory/': typeof DashboardAgentsAgentIdMemoryIndexRoute
  '/agents/$agentId/model/': typeof DashboardAgentsAgentIdModelIndexRoute
  '/agents/$agentId/observe/': typeof DashboardAgentsAgentIdObserveIndexRoute
  '/agents/$agentId/personality/': typeof DashboardAgentsAgentIdPersonalityIndexRoute
  '/agents/$agentId/tools/': typeof DashboardAgentsAgentIdToolsIndexRoute
  '/fleet/instances/$instanceId/': typeof DashboardFleetInstancesInstanceIdIndexRoute
  '/fleet/instances/$instanceId/config/environment': typeof DashboardFleetInstancesInstanceIdConfigEnvironmentRoute
  '/fleet/instances/$instanceId/config/general': typeof DashboardFleetInstancesInstanceIdConfigGeneralRoute
  '/fleet/instances/$instanceId/config/policies': typeof DashboardFleetInstancesInstanceIdConfigPoliciesRoute
  '/fleet/instances/$instanceId/config/providers': typeof DashboardFleetInstancesInstanceIdConfigProvidersRoute
  '/fleet/instances/$instanceId/config/tools': typeof DashboardFleetInstancesInstanceIdConfigToolsRoute
  '/fleet/instances/$instanceId/personalities/agents-md': typeof DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRoute
  '/fleet/instances/$instanceId/personalities/soul': typeof DashboardFleetInstancesInstanceIdPersonalitiesSoulRoute
  '/fleet/instances/$instanceId/config/': typeof DashboardFleetInstancesInstanceIdConfigIndexRoute
  '/fleet/instances/$instanceId/personalities/': typeof DashboardFleetInstancesInstanceIdPersonalitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AppHomeRoute
  '/chat/$agentId': typeof AppChatAgentIdRoute
  '/agents/new': typeof DashboardAgentsNewRoute
  '/audit/config-changes': typeof DashboardAuditConfigChangesRoute
  '/audit/tools': typeof DashboardAuditToolsRoute
  '/observe/cost': typeof DashboardObserveCostRoute
  '/observe/live': typeof DashboardObserveLiveRoute
  '/observe/logs': typeof DashboardObserveLogsRoute
  '/observe/traces': typeof DashboardObserveTracesRoute
  '/security/incidents': typeof DashboardSecurityIncidentsRoute
  '/security/posture': typeof DashboardSecurityPostureRoute
  '/security/quarantine': typeof DashboardSecurityQuarantineRoute
  '/security/secrets': typeof DashboardSecuritySecretsRoute
  '/approvals': typeof AppApprovalsIndexRoute
  '/automations': typeof AppAutomationsIndexRoute
  '/briefing': typeof AppBriefingIndexRoute
  '/chat': typeof AppChatIndexRoute
  '/cron': typeof AppCronIndexRoute
  '/personal': typeof AppPersonalIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/work': typeof AppWorkIndexRoute
  '/agents': typeof DashboardAgentsIndexRoute
  '/audit': typeof DashboardAuditIndexRoute
  '/blueprints': typeof DashboardBlueprintsIndexRoute
  '/channels': typeof DashboardChannelsIndexRoute
  '/configure': typeof DashboardConfigureIndexRoute
  '/fleet': typeof DashboardFleetIndexRoute
  '/observe': typeof DashboardObserveIndexRoute
  '/security': typeof DashboardSecurityIndexRoute
  '/sessions': typeof DashboardSessionsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/skills': typeof DashboardSkillsIndexRoute
  '/swarms': typeof DashboardSwarmsIndexRoute
  '/fleet/instances/new': typeof DashboardFleetInstancesNewRoute
  '/agents/$agentId': typeof DashboardAgentsAgentIdIndexRoute
  '/blueprints/$blueprintId': typeof DashboardBlueprintsBlueprintIdIndexRoute
  '/fleet/instances': typeof DashboardFleetInstancesIndexRoute
  '/sessions/$sessionId': typeof DashboardSessionsSessionIdIndexRoute
  '/swarms/$swarmId': typeof DashboardSwarmsSwarmIdIndexRoute
  '/agents/$agentId/personality/agents-md': typeof DashboardAgentsAgentIdPersonalityAgentsMdRoute
  '/agents/$agentId/personality/soul': typeof DashboardAgentsAgentIdPersonalitySoulRoute
  '/agents/$agentId/personality/user-md': typeof DashboardAgentsAgentIdPersonalityUserMdRoute
  '/agents/$agentId/memory': typeof DashboardAgentsAgentIdMemoryIndexRoute
  '/agents/$agentId/model': typeof DashboardAgentsAgentIdModelIndexRoute
  '/agents/$agentId/observe': typeof DashboardAgentsAgentIdObserveIndexRoute
  '/agents/$agentId/personality': typeof DashboardAgentsAgentIdPersonalityIndexRoute
  '/agents/$agentId/tools': typeof DashboardAgentsAgentIdToolsIndexRoute
  '/fleet/instances/$instanceId': typeof DashboardFleetInstancesInstanceIdIndexRoute
  '/fleet/instances/$instanceId/config/environment': typeof DashboardFleetInstancesInstanceIdConfigEnvironmentRoute
  '/fleet/instances/$instanceId/config/general': typeof DashboardFleetInstancesInstanceIdConfigGeneralRoute
  '/fleet/instances/$instanceId/config/policies': typeof DashboardFleetInstancesInstanceIdConfigPoliciesRoute
  '/fleet/instances/$instanceId/config/providers': typeof DashboardFleetInstancesInstanceIdConfigProvidersRoute
  '/fleet/instances/$instanceId/config/tools': typeof DashboardFleetInstancesInstanceIdConfigToolsRoute
  '/fleet/instances/$instanceId/personalities/agents-md': typeof DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRoute
  '/fleet/instances/$instanceId/personalities/soul': typeof DashboardFleetInstancesInstanceIdPersonalitiesSoulRoute
  '/fleet/instances/$instanceId/config': typeof DashboardFleetInstancesInstanceIdConfigIndexRoute
  '/fleet/instances/$instanceId/personalities': typeof DashboardFleetInstancesInstanceIdPersonalitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/chat/$agentId': typeof AppChatAgentIdRoute
  '/_dashboard/agents/new': typeof DashboardAgentsNewRoute
  '/_dashboard/audit/config-changes': typeof DashboardAuditConfigChangesRoute
  '/_dashboard/audit/tools': typeof DashboardAuditToolsRoute
  '/_dashboard/observe/cost': typeof DashboardObserveCostRoute
  '/_dashboard/observe/live': typeof DashboardObserveLiveRoute
  '/_dashboard/observe/logs': typeof DashboardObserveLogsRoute
  '/_dashboard/observe/traces': typeof DashboardObserveTracesRoute
  '/_dashboard/security/incidents': typeof DashboardSecurityIncidentsRoute
  '/_dashboard/security/posture': typeof DashboardSecurityPostureRoute
  '/_dashboard/security/quarantine': typeof DashboardSecurityQuarantineRoute
  '/_dashboard/security/secrets': typeof DashboardSecuritySecretsRoute
  '/_app/approvals/': typeof AppApprovalsIndexRoute
  '/_app/automations/': typeof AppAutomationsIndexRoute
  '/_app/briefing/': typeof AppBriefingIndexRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/cron/': typeof AppCronIndexRoute
  '/_app/personal/': typeof AppPersonalIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/work/': typeof AppWorkIndexRoute
  '/_dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/_dashboard/audit/': typeof DashboardAuditIndexRoute
  '/_dashboard/blueprints/': typeof DashboardBlueprintsIndexRoute
  '/_dashboard/channels/': typeof DashboardChannelsIndexRoute
  '/_dashboard/configure/': typeof DashboardConfigureIndexRoute
  '/_dashboard/fleet/': typeof DashboardFleetIndexRoute
  '/_dashboard/observe/': typeof DashboardObserveIndexRoute
  '/_dashboard/security/': typeof DashboardSecurityIndexRoute
  '/_dashboard/sessions/': typeof DashboardSessionsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/skills/': typeof DashboardSkillsIndexRoute
  '/_dashboard/swarms/': typeof DashboardSwarmsIndexRoute
  '/_dashboard/fleet/instances/new': typeof DashboardFleetInstancesNewRoute
  '/_dashboard/agents/$agentId/': typeof DashboardAgentsAgentIdIndexRoute
  '/_dashboard/blueprints/$blueprintId/': typeof DashboardBlueprintsBlueprintIdIndexRoute
  '/_dashboard/fleet/instances/': typeof DashboardFleetInstancesIndexRoute
  '/_dashboard/sessions/$sessionId/': typeof DashboardSessionsSessionIdIndexRoute
  '/_dashboard/swarms/$swarmId/': typeof DashboardSwarmsSwarmIdIndexRoute
  '/_dashboard/agents/$agentId/personality/agents-md': typeof DashboardAgentsAgentIdPersonalityAgentsMdRoute
  '/_dashboard/agents/$agentId/personality/soul': typeof DashboardAgentsAgentIdPersonalitySoulRoute
  '/_dashboard/agents/$agentId/personality/user-md': typeof DashboardAgentsAgentIdPersonalityUserMdRoute
  '/_dashboard/agents/$agentId/memory/': typeof DashboardAgentsAgentIdMemoryIndexRoute
  '/_dashboard/agents/$agentId/model/': typeof DashboardAgentsAgentIdModelIndexRoute
  '/_dashboard/agents/$agentId/observe/': typeof DashboardAgentsAgentIdObserveIndexRoute
  '/_dashboard/agents/$agentId/personality/': typeof DashboardAgentsAgentIdPersonalityIndexRoute
  '/_dashboard/agents/$agentId/tools/': typeof DashboardAgentsAgentIdToolsIndexRoute
  '/_dashboard/fleet/instances/$instanceId/': typeof DashboardFleetInstancesInstanceIdIndexRoute
  '/_dashboard/fleet/instances/$instanceId/config/environment': typeof DashboardFleetInstancesInstanceIdConfigEnvironmentRoute
  '/_dashboard/fleet/instances/$instanceId/config/general': typeof DashboardFleetInstancesInstanceIdConfigGeneralRoute
  '/_dashboard/fleet/instances/$instanceId/config/policies': typeof DashboardFleetInstancesInstanceIdConfigPoliciesRoute
  '/_dashboard/fleet/instances/$instanceId/config/providers': typeof DashboardFleetInstancesInstanceIdConfigProvidersRoute
  '/_dashboard/fleet/instances/$instanceId/config/tools': typeof DashboardFleetInstancesInstanceIdConfigToolsRoute
  '/_dashboard/fleet/instances/$instanceId/personalities/agents-md': typeof DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRoute
  '/_dashboard/fleet/instances/$instanceId/personalities/soul': typeof DashboardFleetInstancesInstanceIdPersonalitiesSoulRoute
  '/_dashboard/fleet/instances/$instanceId/config/': typeof DashboardFleetInstancesInstanceIdConfigIndexRoute
  '/_dashboard/fleet/instances/$instanceId/personalities/': typeof DashboardFleetInstancesInstanceIdPersonalitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/chat/$agentId'
    | '/agents/new'
    | '/audit/config-changes'
    | '/audit/tools'
    | '/observe/cost'
    | '/observe/live'
    | '/observe/logs'
    | '/observe/traces'
    | '/security/incidents'
    | '/security/posture'
    | '/security/quarantine'
    | '/security/secrets'
    | '/approvals/'
    | '/automations/'
    | '/briefing/'
    | '/chat/'
    | '/cron/'
    | '/personal/'
    | '/projects/'
    | '/tasks/'
    | '/work/'
    | '/agents/'
    | '/audit/'
    | '/blueprints/'
    | '/channels/'
    | '/configure/'
    | '/fleet/'
    | '/observe/'
    | '/security/'
    | '/sessions/'
    | '/settings/'
    | '/skills/'
    | '/swarms/'
    | '/fleet/instances/new'
    | '/agents/$agentId/'
    | '/blueprints/$blueprintId/'
    | '/fleet/instances/'
    | '/sessions/$sessionId/'
    | '/swarms/$swarmId/'
    | '/agents/$agentId/personality/agents-md'
    | '/agents/$agentId/personality/soul'
    | '/agents/$agentId/personality/user-md'
    | '/agents/$agentId/memory/'
    | '/agents/$agentId/model/'
    | '/agents/$agentId/observe/'
    | '/agents/$agentId/personality/'
    | '/agents/$agentId/tools/'
    | '/fleet/instances/$instanceId/'
    | '/fleet/instances/$instanceId/config/environment'
    | '/fleet/instances/$instanceId/config/general'
    | '/fleet/instances/$instanceId/config/policies'
    | '/fleet/instances/$instanceId/config/providers'
    | '/fleet/instances/$instanceId/config/tools'
    | '/fleet/instances/$instanceId/personalities/agents-md'
    | '/fleet/instances/$instanceId/personalities/soul'
    | '/fleet/instances/$instanceId/config/'
    | '/fleet/instances/$instanceId/personalities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/chat/$agentId'
    | '/agents/new'
    | '/audit/config-changes'
    | '/audit/tools'
    | '/observe/cost'
    | '/observe/live'
    | '/observe/logs'
    | '/observe/traces'
    | '/security/incidents'
    | '/security/posture'
    | '/security/quarantine'
    | '/security/secrets'
    | '/approvals'
    | '/automations'
    | '/briefing'
    | '/chat'
    | '/cron'
    | '/personal'
    | '/projects'
    | '/tasks'
    | '/work'
    | '/agents'
    | '/audit'
    | '/blueprints'
    | '/channels'
    | '/configure'
    | '/fleet'
    | '/observe'
    | '/security'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/swarms'
    | '/fleet/instances/new'
    | '/agents/$agentId'
    | '/blueprints/$blueprintId'
    | '/fleet/instances'
    | '/sessions/$sessionId'
    | '/swarms/$swarmId'
    | '/agents/$agentId/personality/agents-md'
    | '/agents/$agentId/personality/soul'
    | '/agents/$agentId/personality/user-md'
    | '/agents/$agentId/memory'
    | '/agents/$agentId/model'
    | '/agents/$agentId/observe'
    | '/agents/$agentId/personality'
    | '/agents/$agentId/tools'
    | '/fleet/instances/$instanceId'
    | '/fleet/instances/$instanceId/config/environment'
    | '/fleet/instances/$instanceId/config/general'
    | '/fleet/instances/$instanceId/config/policies'
    | '/fleet/instances/$instanceId/config/providers'
    | '/fleet/instances/$instanceId/config/tools'
    | '/fleet/instances/$instanceId/personalities/agents-md'
    | '/fleet/instances/$instanceId/personalities/soul'
    | '/fleet/instances/$instanceId/config'
    | '/fleet/instances/$instanceId/personalities'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_dashboard'
    | '/_app/home'
    | '/_app/chat/$agentId'
    | '/_dashboard/agents/new'
    | '/_dashboard/audit/config-changes'
    | '/_dashboard/audit/tools'
    | '/_dashboard/observe/cost'
    | '/_dashboard/observe/live'
    | '/_dashboard/observe/logs'
    | '/_dashboard/observe/traces'
    | '/_dashboard/security/incidents'
    | '/_dashboard/security/posture'
    | '/_dashboard/security/quarantine'
    | '/_dashboard/security/secrets'
    | '/_app/approvals/'
    | '/_app/automations/'
    | '/_app/briefing/'
    | '/_app/chat/'
    | '/_app/cron/'
    | '/_app/personal/'
    | '/_app/projects/'
    | '/_app/tasks/'
    | '/_app/work/'
    | '/_dashboard/agents/'
    | '/_dashboard/audit/'
    | '/_dashboard/blueprints/'
    | '/_dashboard/channels/'
    | '/_dashboard/configure/'
    | '/_dashboard/fleet/'
    | '/_dashboard/observe/'
    | '/_dashboard/security/'
    | '/_dashboard/sessions/'
    | '/_dashboard/settings/'
    | '/_dashboard/skills/'
    | '/_dashboard/swarms/'
    | '/_dashboard/fleet/instances/new'
    | '/_dashboard/agents/$agentId/'
    | '/_dashboard/blueprints/$blueprintId/'
    | '/_dashboard/fleet/instances/'
    | '/_dashboard/sessions/$sessionId/'
    | '/_dashboard/swarms/$swarmId/'
    | '/_dashboard/agents/$agentId/personality/agents-md'
    | '/_dashboard/agents/$agentId/personality/soul'
    | '/_dashboard/agents/$agentId/personality/user-md'
    | '/_dashboard/agents/$agentId/memory/'
    | '/_dashboard/agents/$agentId/model/'
    | '/_dashboard/agents/$agentId/observe/'
    | '/_dashboard/agents/$agentId/personality/'
    | '/_dashboard/agents/$agentId/tools/'
    | '/_dashboard/fleet/instances/$instanceId/'
    | '/_dashboard/fleet/instances/$instanceId/config/environment'
    | '/_dashboard/fleet/instances/$instanceId/config/general'
    | '/_dashboard/fleet/instances/$instanceId/config/policies'
    | '/_dashboard/fleet/instances/$instanceId/config/providers'
    | '/_dashboard/fleet/instances/$instanceId/config/tools'
    | '/_dashboard/fleet/instances/$instanceId/personalities/agents-md'
    | '/_dashboard/fleet/instances/$instanceId/personalities/soul'
    | '/_dashboard/fleet/instances/$instanceId/config/'
    | '/_dashboard/fleet/instances/$instanceId/personalities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_dashboard/swarms/': {
      id: '/_dashboard/swarms/'
      path: '/swarms'
      fullPath: '/swarms/'
      preLoaderRoute: typeof DashboardSwarmsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/skills/': {
      id: '/_dashboard/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof DashboardSkillsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sessions/': {
      id: '/_dashboard/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof DashboardSessionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/security/': {
      id: '/_dashboard/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof DashboardSecurityIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/observe/': {
      id: '/_dashboard/observe/'
      path: '/observe'
      fullPath: '/observe/'
      preLoaderRoute: typeof DashboardObserveIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/': {
      id: '/_dashboard/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof DashboardFleetIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/configure/': {
      id: '/_dashboard/configure/'
      path: '/configure'
      fullPath: '/configure/'
      preLoaderRoute: typeof DashboardConfigureIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/channels/': {
      id: '/_dashboard/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof DashboardChannelsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blueprints/': {
      id: '/_dashboard/blueprints/'
      path: '/blueprints'
      fullPath: '/blueprints/'
      preLoaderRoute: typeof DashboardBlueprintsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit/': {
      id: '/_dashboard/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof DashboardAuditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/': {
      id: '/_dashboard/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_app/work/': {
      id: '/_app/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof AppWorkIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personal/': {
      id: '/_app/personal/'
      path: '/personal'
      fullPath: '/personal/'
      preLoaderRoute: typeof AppPersonalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cron/': {
      id: '/_app/cron/'
      path: '/cron'
      fullPath: '/cron/'
      preLoaderRoute: typeof AppCronIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/briefing/': {
      id: '/_app/briefing/'
      path: '/briefing'
      fullPath: '/briefing/'
      preLoaderRoute: typeof AppBriefingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations/': {
      id: '/_app/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AppAutomationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals/': {
      id: '/_app/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AppApprovalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_dashboard/security/secrets': {
      id: '/_dashboard/security/secrets'
      path: '/security/secrets'
      fullPath: '/security/secrets'
      preLoaderRoute: typeof DashboardSecuritySecretsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/security/quarantine': {
      id: '/_dashboard/security/quarantine'
      path: '/security/quarantine'
      fullPath: '/security/quarantine'
      preLoaderRoute: typeof DashboardSecurityQuarantineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/security/posture': {
      id: '/_dashboard/security/posture'
      path: '/security/posture'
      fullPath: '/security/posture'
      preLoaderRoute: typeof DashboardSecurityPostureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/security/incidents': {
      id: '/_dashboard/security/incidents'
      path: '/security/incidents'
      fullPath: '/security/incidents'
      preLoaderRoute: typeof DashboardSecurityIncidentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/observe/traces': {
      id: '/_dashboard/observe/traces'
      path: '/observe/traces'
      fullPath: '/observe/traces'
      preLoaderRoute: typeof DashboardObserveTracesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/observe/logs': {
      id: '/_dashboard/observe/logs'
      path: '/observe/logs'
      fullPath: '/observe/logs'
      preLoaderRoute: typeof DashboardObserveLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/observe/live': {
      id: '/_dashboard/observe/live'
      path: '/observe/live'
      fullPath: '/observe/live'
      preLoaderRoute: typeof DashboardObserveLiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/observe/cost': {
      id: '/_dashboard/observe/cost'
      path: '/observe/cost'
      fullPath: '/observe/cost'
      preLoaderRoute: typeof DashboardObserveCostRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit/tools': {
      id: '/_dashboard/audit/tools'
      path: '/audit/tools'
      fullPath: '/audit/tools'
      preLoaderRoute: typeof DashboardAuditToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit/config-changes': {
      id: '/_dashboard/audit/config-changes'
      path: '/audit/config-changes'
      fullPath: '/audit/config-changes'
      preLoaderRoute: typeof DashboardAuditConfigChangesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/new': {
      id: '/_dashboard/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof DashboardAgentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_app/chat/$agentId': {
      id: '/_app/chat/$agentId'
      path: '/chat/$agentId'
      fullPath: '/chat/$agentId'
      preLoaderRoute: typeof AppChatAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_dashboard/swarms/$swarmId/': {
      id: '/_dashboard/swarms/$swarmId/'
      path: '/swarms/$swarmId'
      fullPath: '/swarms/$swarmId/'
      preLoaderRoute: typeof DashboardSwarmsSwarmIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sessions/$sessionId/': {
      id: '/_dashboard/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof DashboardSessionsSessionIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/': {
      id: '/_dashboard/fleet/instances/'
      path: '/fleet/instances'
      fullPath: '/fleet/instances/'
      preLoaderRoute: typeof DashboardFleetInstancesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blueprints/$blueprintId/': {
      id: '/_dashboard/blueprints/$blueprintId/'
      path: '/blueprints/$blueprintId'
      fullPath: '/blueprints/$blueprintId/'
      preLoaderRoute: typeof DashboardBlueprintsBlueprintIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/': {
      id: '/_dashboard/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof DashboardAgentsAgentIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/new': {
      id: '/_dashboard/fleet/instances/new'
      path: '/fleet/instances/new'
      fullPath: '/fleet/instances/new'
      preLoaderRoute: typeof DashboardFleetInstancesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/': {
      id: '/_dashboard/fleet/instances/$instanceId/'
      path: '/fleet/instances/$instanceId'
      fullPath: '/fleet/instances/$instanceId/'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/tools/': {
      id: '/_dashboard/agents/$agentId/tools/'
      path: '/agents/$agentId/tools'
      fullPath: '/agents/$agentId/tools/'
      preLoaderRoute: typeof DashboardAgentsAgentIdToolsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/personality/': {
      id: '/_dashboard/agents/$agentId/personality/'
      path: '/agents/$agentId/personality'
      fullPath: '/agents/$agentId/personality/'
      preLoaderRoute: typeof DashboardAgentsAgentIdPersonalityIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/observe/': {
      id: '/_dashboard/agents/$agentId/observe/'
      path: '/agents/$agentId/observe'
      fullPath: '/agents/$agentId/observe/'
      preLoaderRoute: typeof DashboardAgentsAgentIdObserveIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/model/': {
      id: '/_dashboard/agents/$agentId/model/'
      path: '/agents/$agentId/model'
      fullPath: '/agents/$agentId/model/'
      preLoaderRoute: typeof DashboardAgentsAgentIdModelIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/memory/': {
      id: '/_dashboard/agents/$agentId/memory/'
      path: '/agents/$agentId/memory'
      fullPath: '/agents/$agentId/memory/'
      preLoaderRoute: typeof DashboardAgentsAgentIdMemoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/personality/user-md': {
      id: '/_dashboard/agents/$agentId/personality/user-md'
      path: '/agents/$agentId/personality/user-md'
      fullPath: '/agents/$agentId/personality/user-md'
      preLoaderRoute: typeof DashboardAgentsAgentIdPersonalityUserMdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/personality/soul': {
      id: '/_dashboard/agents/$agentId/personality/soul'
      path: '/agents/$agentId/personality/soul'
      fullPath: '/agents/$agentId/personality/soul'
      preLoaderRoute: typeof DashboardAgentsAgentIdPersonalitySoulRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/personality/agents-md': {
      id: '/_dashboard/agents/$agentId/personality/agents-md'
      path: '/agents/$agentId/personality/agents-md'
      fullPath: '/agents/$agentId/personality/agents-md'
      preLoaderRoute: typeof DashboardAgentsAgentIdPersonalityAgentsMdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/personalities/': {
      id: '/_dashboard/fleet/instances/$instanceId/personalities/'
      path: '/fleet/instances/$instanceId/personalities'
      fullPath: '/fleet/instances/$instanceId/personalities/'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdPersonalitiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/config/': {
      id: '/_dashboard/fleet/instances/$instanceId/config/'
      path: '/fleet/instances/$instanceId/config'
      fullPath: '/fleet/instances/$instanceId/config/'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdConfigIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/personalities/soul': {
      id: '/_dashboard/fleet/instances/$instanceId/personalities/soul'
      path: '/fleet/instances/$instanceId/personalities/soul'
      fullPath: '/fleet/instances/$instanceId/personalities/soul'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdPersonalitiesSoulRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/personalities/agents-md': {
      id: '/_dashboard/fleet/instances/$instanceId/personalities/agents-md'
      path: '/fleet/instances/$instanceId/personalities/agents-md'
      fullPath: '/fleet/instances/$instanceId/personalities/agents-md'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/config/tools': {
      id: '/_dashboard/fleet/instances/$instanceId/config/tools'
      path: '/fleet/instances/$instanceId/config/tools'
      fullPath: '/fleet/instances/$instanceId/config/tools'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdConfigToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/config/providers': {
      id: '/_dashboard/fleet/instances/$instanceId/config/providers'
      path: '/fleet/instances/$instanceId/config/providers'
      fullPath: '/fleet/instances/$instanceId/config/providers'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdConfigProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/config/policies': {
      id: '/_dashboard/fleet/instances/$instanceId/config/policies'
      path: '/fleet/instances/$instanceId/config/policies'
      fullPath: '/fleet/instances/$instanceId/config/policies'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdConfigPoliciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/config/general': {
      id: '/_dashboard/fleet/instances/$instanceId/config/general'
      path: '/fleet/instances/$instanceId/config/general'
      fullPath: '/fleet/instances/$instanceId/config/general'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdConfigGeneralRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fleet/instances/$instanceId/config/environment': {
      id: '/_dashboard/fleet/instances/$instanceId/config/environment'
      path: '/fleet/instances/$instanceId/config/environment'
      fullPath: '/fleet/instances/$instanceId/config/environment'
      preLoaderRoute: typeof DashboardFleetInstancesInstanceIdConfigEnvironmentRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppChatAgentIdRoute: typeof AppChatAgentIdRoute
  AppApprovalsIndexRoute: typeof AppApprovalsIndexRoute
  AppAutomationsIndexRoute: typeof AppAutomationsIndexRoute
  AppBriefingIndexRoute: typeof AppBriefingIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppCronIndexRoute: typeof AppCronIndexRoute
  AppPersonalIndexRoute: typeof AppPersonalIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppWorkIndexRoute: typeof AppWorkIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppChatAgentIdRoute: AppChatAgentIdRoute,
  AppApprovalsIndexRoute: AppApprovalsIndexRoute,
  AppAutomationsIndexRoute: AppAutomationsIndexRoute,
  AppBriefingIndexRoute: AppBriefingIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppCronIndexRoute: AppCronIndexRoute,
  AppPersonalIndexRoute: AppPersonalIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppWorkIndexRoute: AppWorkIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentsNewRoute: typeof DashboardAgentsNewRoute
  DashboardAuditConfigChangesRoute: typeof DashboardAuditConfigChangesRoute
  DashboardAuditToolsRoute: typeof DashboardAuditToolsRoute
  DashboardObserveCostRoute: typeof DashboardObserveCostRoute
  DashboardObserveLiveRoute: typeof DashboardObserveLiveRoute
  DashboardObserveLogsRoute: typeof DashboardObserveLogsRoute
  DashboardObserveTracesRoute: typeof DashboardObserveTracesRoute
  DashboardSecurityIncidentsRoute: typeof DashboardSecurityIncidentsRoute
  DashboardSecurityPostureRoute: typeof DashboardSecurityPostureRoute
  DashboardSecurityQuarantineRoute: typeof DashboardSecurityQuarantineRoute
  DashboardSecuritySecretsRoute: typeof DashboardSecuritySecretsRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
  DashboardAuditIndexRoute: typeof DashboardAuditIndexRoute
  DashboardBlueprintsIndexRoute: typeof DashboardBlueprintsIndexRoute
  DashboardChannelsIndexRoute: typeof DashboardChannelsIndexRoute
  DashboardConfigureIndexRoute: typeof DashboardConfigureIndexRoute
  DashboardFleetIndexRoute: typeof DashboardFleetIndexRoute
  DashboardObserveIndexRoute: typeof DashboardObserveIndexRoute
  DashboardSecurityIndexRoute: typeof DashboardSecurityIndexRoute
  DashboardSessionsIndexRoute: typeof DashboardSessionsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSkillsIndexRoute: typeof DashboardSkillsIndexRoute
  DashboardSwarmsIndexRoute: typeof DashboardSwarmsIndexRoute
  DashboardFleetInstancesNewRoute: typeof DashboardFleetInstancesNewRoute
  DashboardAgentsAgentIdIndexRoute: typeof DashboardAgentsAgentIdIndexRoute
  DashboardBlueprintsBlueprintIdIndexRoute: typeof DashboardBlueprintsBlueprintIdIndexRoute
  DashboardFleetInstancesIndexRoute: typeof DashboardFleetInstancesIndexRoute
  DashboardSessionsSessionIdIndexRoute: typeof DashboardSessionsSessionIdIndexRoute
  DashboardSwarmsSwarmIdIndexRoute: typeof DashboardSwarmsSwarmIdIndexRoute
  DashboardAgentsAgentIdPersonalityAgentsMdRoute: typeof DashboardAgentsAgentIdPersonalityAgentsMdRoute
  DashboardAgentsAgentIdPersonalitySoulRoute: typeof DashboardAgentsAgentIdPersonalitySoulRoute
  DashboardAgentsAgentIdPersonalityUserMdRoute: typeof DashboardAgentsAgentIdPersonalityUserMdRoute
  DashboardAgentsAgentIdMemoryIndexRoute: typeof DashboardAgentsAgentIdMemoryIndexRoute
  DashboardAgentsAgentIdModelIndexRoute: typeof DashboardAgentsAgentIdModelIndexRoute
  DashboardAgentsAgentIdObserveIndexRoute: typeof DashboardAgentsAgentIdObserveIndexRoute
  DashboardAgentsAgentIdPersonalityIndexRoute: typeof DashboardAgentsAgentIdPersonalityIndexRoute
  DashboardAgentsAgentIdToolsIndexRoute: typeof DashboardAgentsAgentIdToolsIndexRoute
  DashboardFleetInstancesInstanceIdIndexRoute: typeof DashboardFleetInstancesInstanceIdIndexRoute
  DashboardFleetInstancesInstanceIdConfigEnvironmentRoute: typeof DashboardFleetInstancesInstanceIdConfigEnvironmentRoute
  DashboardFleetInstancesInstanceIdConfigGeneralRoute: typeof DashboardFleetInstancesInstanceIdConfigGeneralRoute
  DashboardFleetInstancesInstanceIdConfigPoliciesRoute: typeof DashboardFleetInstancesInstanceIdConfigPoliciesRoute
  DashboardFleetInstancesInstanceIdConfigProvidersRoute: typeof DashboardFleetInstancesInstanceIdConfigProvidersRoute
  DashboardFleetInstancesInstanceIdConfigToolsRoute: typeof DashboardFleetInstancesInstanceIdConfigToolsRoute
  DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRoute: typeof DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRoute
  DashboardFleetInstancesInstanceIdPersonalitiesSoulRoute: typeof DashboardFleetInstancesInstanceIdPersonalitiesSoulRoute
  DashboardFleetInstancesInstanceIdConfigIndexRoute: typeof DashboardFleetInstancesInstanceIdConfigIndexRoute
  DashboardFleetInstancesInstanceIdPersonalitiesIndexRoute: typeof DashboardFleetInstancesInstanceIdPersonalitiesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsNewRoute: DashboardAgentsNewRoute,
  DashboardAuditConfigChangesRoute: DashboardAuditConfigChangesRoute,
  DashboardAuditToolsRoute: DashboardAuditToolsRoute,
  DashboardObserveCostRoute: DashboardObserveCostRoute,
  DashboardObserveLiveRoute: DashboardObserveLiveRoute,
  DashboardObserveLogsRoute: DashboardObserveLogsRoute,
  DashboardObserveTracesRoute: DashboardObserveTracesRoute,
  DashboardSecurityIncidentsRoute: DashboardSecurityIncidentsRoute,
  DashboardSecurityPostureRoute: DashboardSecurityPostureRoute,
  DashboardSecurityQuarantineRoute: DashboardSecurityQuarantineRoute,
  DashboardSecuritySecretsRoute: DashboardSecuritySecretsRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
  DashboardAuditIndexRoute: DashboardAuditIndexRoute,
  DashboardBlueprintsIndexRoute: DashboardBlueprintsIndexRoute,
  DashboardChannelsIndexRoute: DashboardChannelsIndexRoute,
  DashboardConfigureIndexRoute: DashboardConfigureIndexRoute,
  DashboardFleetIndexRoute: DashboardFleetIndexRoute,
  DashboardObserveIndexRoute: DashboardObserveIndexRoute,
  DashboardSecurityIndexRoute: DashboardSecurityIndexRoute,
  DashboardSessionsIndexRoute: DashboardSessionsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardSkillsIndexRoute: DashboardSkillsIndexRoute,
  DashboardSwarmsIndexRoute: DashboardSwarmsIndexRoute,
  DashboardFleetInstancesNewRoute: DashboardFleetInstancesNewRoute,
  DashboardAgentsAgentIdIndexRoute: DashboardAgentsAgentIdIndexRoute,
  DashboardBlueprintsBlueprintIdIndexRoute:
    DashboardBlueprintsBlueprintIdIndexRoute,
  DashboardFleetInstancesIndexRoute: DashboardFleetInstancesIndexRoute,
  DashboardSessionsSessionIdIndexRoute: DashboardSessionsSessionIdIndexRoute,
  DashboardSwarmsSwarmIdIndexRoute: DashboardSwarmsSwarmIdIndexRoute,
  DashboardAgentsAgentIdPersonalityAgentsMdRoute:
    DashboardAgentsAgentIdPersonalityAgentsMdRoute,
  DashboardAgentsAgentIdPersonalitySoulRoute:
    DashboardAgentsAgentIdPersonalitySoulRoute,
  DashboardAgentsAgentIdPersonalityUserMdRoute:
    DashboardAgentsAgentIdPersonalityUserMdRoute,
  DashboardAgentsAgentIdMemoryIndexRoute:
    DashboardAgentsAgentIdMemoryIndexRoute,
  DashboardAgentsAgentIdModelIndexRoute: DashboardAgentsAgentIdModelIndexRoute,
  DashboardAgentsAgentIdObserveIndexRoute:
    DashboardAgentsAgentIdObserveIndexRoute,
  DashboardAgentsAgentIdPersonalityIndexRoute:
    DashboardAgentsAgentIdPersonalityIndexRoute,
  DashboardAgentsAgentIdToolsIndexRoute: DashboardAgentsAgentIdToolsIndexRoute,
  DashboardFleetInstancesInstanceIdIndexRoute:
    DashboardFleetInstancesInstanceIdIndexRoute,
  DashboardFleetInstancesInstanceIdConfigEnvironmentRoute:
    DashboardFleetInstancesInstanceIdConfigEnvironmentRoute,
  DashboardFleetInstancesInstanceIdConfigGeneralRoute:
    DashboardFleetInstancesInstanceIdConfigGeneralRoute,
  DashboardFleetInstancesInstanceIdConfigPoliciesRoute:
    DashboardFleetInstancesInstanceIdConfigPoliciesRoute,
  DashboardFleetInstancesInstanceIdConfigProvidersRoute:
    DashboardFleetInstancesInstanceIdConfigProvidersRoute,
  DashboardFleetInstancesInstanceIdConfigToolsRoute:
    DashboardFleetInstancesInstanceIdConfigToolsRoute,
  DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRoute:
    DashboardFleetInstancesInstanceIdPersonalitiesAgentsMdRoute,
  DashboardFleetInstancesInstanceIdPersonalitiesSoulRoute:
    DashboardFleetInstancesInstanceIdPersonalitiesSoulRoute,
  DashboardFleetInstancesInstanceIdConfigIndexRoute:
    DashboardFleetInstancesInstanceIdConfigIndexRoute,
  DashboardFleetInstancesInstanceIdPersonalitiesIndexRoute:
    DashboardFleetInstancesInstanceIdPersonalitiesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
